"""Check profit target settings for commodities and crypto."""

print("=" * 80)
print("PROFIT TARGET SETTINGS - COMMODITIES vs CRYPTO")
print("=" * 80)
print()

print("COMMODITIES:")
print("  Script: trade_commodities_angelone.py")
print("  Argument: --profit-target-pct")
print("  Status: REQUIRED (no default)")
print("  Example: --profit-target-pct 0.5 (for 0.5% profit)")
print()

print("CRYPTO:")
print("  Script: end_to_end_crypto.py")
print("  Argument: --profit-target")
print("  Status: REQUIRED (no default)")
print("  Example: --profit-target 10.0 (for 10% profit)")
print()

print("=" * 80)
print("TAKE-PROFIT RISK MULTIPLE (Reference Only)")
print("=" * 80)
print()
print("There is a 'take_profit_risk_multiple' setting (default: 2.0)")
print("This calculates: take_profit = stop_loss * 2.0")
print()
print("However, this is ONLY used for broker-level take-profit orders.")
print("The actual profit target that the system monitors is ALWAYS")
print("the user-specified --profit-target-pct (commodities) or")
print("--profit-target (crypto).")
print()

print("=" * 80)
print("CONCLUSION")
print("=" * 80)
print()
print("NO DEFAULT PROFIT TARGET exists for either commodities or crypto.")
print("Both require explicit user specification.")
print()
print("The take_profit_risk_multiple (2.0x stop-loss) is used for")
print("broker-level order placement, but the monitored profit target")
print("is always the user-specified value.")
print()

