"""
Explain why portfolio shows loss vs trade analysis.
"""

print("=" * 100)
print("WHY YOUR PORTFOLIO SHOWS A LOSS")
print("=" * 100)
print()

print("PORTFOLIO DASHBOARD DATA:")
print("-" * 100)
print("  Current Portfolio Value: $89,238.00")
print("  Daily Change: -$7,959.05")
print("  Percentage Change: -8.19%")
print("  Starting Value (estimated): ~$97,197")
print()

print("TRADE ANALYSIS FROM IMAGES:")
print("-" * 100)
print("  Net Profit from Visible Trades: +$1,205.26")
print("  (This only includes trades shown in your screenshots)")
print()

print("WHY THE DISCREPANCY?")
print("-" * 100)
print()
print("1. INCOMPLETE DATA:")
print("   [X] The images you shared show only SOME trades (about 145 transactions)")
print("   [X] Your actual trading history likely has MANY MORE trades")
print("   [X] The +$1,205.26 profit is only from the visible subset")
print()
print("2. UNREALIZED LOSSES:")
print("   [X] Portfolio value includes OPEN POSITIONS at current market prices")
print("   [X] If you're holding assets that dropped in value, that's an unrealized loss")
print("   [X] This loss is reflected in your portfolio value but not in completed trades")
print()
print("3. MARKET MOVEMENT:")
print("   [X] Even if trades were profitable when closed, your remaining positions")
print("      may have lost value since entry")
print("   [X] Portfolio shows current market value, not just trade profits")
print()
print("4. TIMING DIFFERENCES:")
print("   [X] The trades in images are from Jan 6, 2026")
print("   [X] Portfolio snapshot is from Jan 7, 2026 at 11:52 AM")
print("   [X] Assets may have moved against you overnight")
print()
print("5. TRANSACTION COSTS:")
print("   [X] Fees, spreads, and slippage reduce actual profits")
print("   [X] Simple buy/sell calculation doesn't account for these costs")
print()

print("WHAT YOU SHOULD CHECK:")
print("-" * 100)
print("1. Check your active positions - are any currently underwater?")
print("2. Review ALL trades (not just the ones in images)")
print("3. Look at the full trading log: logs/trading/crypto_trades.jsonl")
print("4. Check if positions hit stop-losses or were closed at losses")
print("5. Verify the portfolio started higher - it dropped from ~$97k to $89k")
print()

print("TO GET ACCURATE P/L:")
print("-" * 100)
print("  Run: python view_trade_logs.py")
print("  This will show realized P/L from ALL trades in your log file")
print()
